// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDezyw6WRgONXtdPcDYgRbqpccjPCIbMeM',
    appId: '1:975466675623:web:88c8578a30312fbe2dca82',
    messagingSenderId: '975466675623',
    projectId: 'flutter-mobil-sigortacilik',
    authDomain: 'flutter-mobil-sigortacilik.firebaseapp.com',
    storageBucket: 'flutter-mobil-sigortacilik.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVRE24IKSmEy2QOB88xgZkX9Nrmo0KOSc',
    appId: '1:975466675623:android:03bed1dca9b282402dca82',
    messagingSenderId: '975466675623',
    projectId: 'flutter-mobil-sigortacilik',
    storageBucket: 'flutter-mobil-sigortacilik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGh4orEExwpYhaRbhxUXzoxODwvKz-ZJU',
    appId: '1:975466675623:ios:327ee8608c35a76a2dca82',
    messagingSenderId: '975466675623',
    projectId: 'flutter-mobil-sigortacilik',
    storageBucket: 'flutter-mobil-sigortacilik.firebasestorage.app',
    iosBundleId: 'com.example.flutterSigorta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDezyw6WRgONXtdPcDYgRbqpccjPCIbMeM',
    appId: '1:975466675623:web:4a862ce602b0db1e2dca82',
    messagingSenderId: '975466675623',
    projectId: 'flutter-mobil-sigortacilik',
    authDomain: 'flutter-mobil-sigortacilik.firebaseapp.com',
    storageBucket: 'flutter-mobil-sigortacilik.firebasestorage.app',
  );
}
